version: "2.1"
services:
  aad-pricing:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: prod
    image: pricing
    ports:
      - "7071:8050"

  aad-pricing-tests:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: tests
    image: test
    volumes:
      - testResults:/var/lib/docker/volumes/aad-pricing_testResults/_data

volumes:
  testResults:
