version: "2.1"
services:
  aad-pricing:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: prod
    container_name: aad-pricing
    image: pricing
    ports:
      - "7071:8050"

  aad-pricing-test-local:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: tests
    container_name: aad-pricing-tests
    image: test
    command: poetry run pytest --junitxml=test-reports/test-results.xml
    volumes:
      - '${PWD}:/testRunner'
      - '${PWD}/test-reports:/testRunner/allure'
      - '${PWD}/tests:/testRunner/tests'

volumes:
  test-reports:
  tests:


